spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3

rabbitmq:
  queue:
    proposta:
      pendente: proposta-pendente.ms-analise-credito
      concluida: proposta-concluida.ms-proposta

  propostaconcluida:
    exchange: proposta-concluida.ex

aws:
  acessKey: ${ACESS_KEY}
  secretKey: ${SECRET_KEY}
