spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    proposta:
      pendente: proposta-pendente.ms-analise-credito
      concluida: proposta-concluida.ms-proposta

  propostaconcluida:
    exchange: proposta-concluida.ex

aws:
  acessKey: ${ACESS_KEY}
  secretKey: ${SECRET_KEY}
